### ISSUE TITLE
Docker doesn't run with docker-compose

### ISSUE THREAD

**Issue by rpedrica** [SickChill/SickChill#6868]
I had a lot of issues running the docker image using the supplied docker-compose script here:

https://github.com/SickChill/SickChill/wiki/Docker

Specifically, I would get the following:

```
WARNING: The USERDIR variable is not set. Defaulting to a blank string.
WARNING: The SHOWS_AND_DOWNLOADS_ROOT variable is not set. Defaulting to a blank string.
```

So this is for those also having issues.

docker-compose refused to pick up the variables specified in the file to perform:

1. variable substitution in the file (for the paths)
2. the user and group specs to set the user the container runs as (not who runs the container)

I ended up doing two things:

.env file for the paths:

```
USERDIR=<path>
SHOWS_AND_DOWNLOADS_ROOT=<path>
```

So these values in the .yml file now substitute correctly from being set in .env..

And then to set the user/group to run as (so that files are owned by the specified user and not who the container was run by):

`    user: 1000:100`

My complete docker-compose.yml is now:

```
---
version: "3.3"
services:
  sickchill:
    container_name: sickchill
    image: sickchill/sickchill
    user: 1000:100
    environment:
      - TZ=Africa/Johannesburg
    volumes:
      - $USERDIR/sickchill:/config
      - $USERDIR/sickchill:/data
      - $SHOWS_AND_DOWNLOADS_ROOT:$SHOWS_AND_DOWNLOADS_ROOT
    ports:
      - 8081:8081
    network_mode: host
    restart: unless-stopped
```

Hope this helps others.

Regards, Robby
