### ISSUE TITLE
Update on docker fails (cross-device link)

### ISSUE THREAD

**Issue by disl-pdavid** [SickChill/SickChill#8113]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Docker
Browser: Firefox
What you did: Attempt to update through the web interface
What happened: Failed to update
What you expected: Update! :)
Logs:
```
2022-08-25 21:29:04 ERROR :: WEBSERVER-HOME_0 :: Error while trying to update: [Errno 18] Invalid cross-device link: '/data/sc-update/SickChill-SickChill-cc9de09/docker-compose.yaml' -> '/app/sickchill/docker-compose.yaml'
```

When using docker, the updates through the web interface fail due to the volumes being seen by the container as separate volumes.
Looks like this is happening after downloading the update and moving the files into /apps/sickchill.

Also seems like there might be a cross-volume way of moving files in Python that would avoid this problem?  (Sorry, not very good at Py so I'm not sure).

Is there a method for manually updating inside the container?

Relevant docker-compose.yml:

```yml
version: "3.3"
services:
  sickchill:
    container_name: sickchill
    image: sickchill/sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      # - USERDIR=/home/user/docker/sickchill
      # - SHOWS_AND_DOWNLOADS_ROOT=/home/user/docker/sickchill/showsdownloadsroot
    volumes:
        # The main app - to keep updates
      - ./sickchill/app:/app
        # The config files
      - ./sickchill/config:/config
        # The sickchill data dir
      - ./sickchill/data:/data
        # The location of TV media
      - /media/Media/TV:/media/TV
        # downloads location from torrent client
      - /home/user/Downloads/complete:/media/downloads/complete
        # unpack directory tmp location
      - /home/user/Downloads/sickchill-unpack:/media/downloads/sickchill-unpack
      - ./sickchill/downloads:/downloads
      - ./sickchill/cache:/app/sickchill/sickchill/gui/slick/cache
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8081:8081
    network_mode: host
    restart: unless-stopped

```
